<a href="https://colab.research.google.com/github/Mugees4u/M4u/blob/master/NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Empty Array: create an uninitialized array of specified shape and data type on runtime

### Sysntax:
### np.empty(shape, dtype, order)
## dtype - float  (default)
## order = 'c'  (dfault)

In [1]:
import numpy as np
np.empty((2,3))

array([[2.2539496e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [2]:
#prog:
import numpy as np

a = np.empty((3, 2), dtype=int)
print(a)

[[45620448        0]
 [       0        0]
 [       0        0]]


## Basic characterstics of Array

In [3]:
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5]])
print("Array:\n", a)

# types of array
print("Array is type of:\n", type(a))

#dimension of array
print('Dimension of array:\n', a.ndim)

#shape of an array
print('shape of array:\n', a.shape)

# Size of an array
print('Size of an array:\n', a.size)

#Types of elements in array
print('Elements types:\n', a.dtype)

Array:
 [[1 2 3]
 [3 4 5]]
Array is type of:
 <class 'numpy.ndarray'>
Dimension of array:
 2
shape of array:
 (2, 3)
Size of an array:
 6
Elements types:
 int64


In [4]:
import numpy as np
x = np.array([[6, 7, 8], [7, 8.5, 13], [14, 12, 16]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[ 6.   7.   8. ]
 [ 7.   8.5 13. ]
 [14.  12.  16. ]]
2
(3, 3)
9
float64


## Create an array from list

In [5]:
import numpy as np
l1 = np.array([6, 8, 9])
print(l1)

print(l1.size)  # size of array

print(l1.ndim)  # dimension of array

print(l1.shape)  #shape of array

print(l1.dtype)

print(type(l1))   # types of array

[6 8 9]
3
1
(3,)
int64
<class 'numpy.ndarray'>


In [6]:
# Prog. create an array from list

menu = np.array(['Pizza', 'Pasta', 'Mecroni'])
print(menu)

#dtypes of an array
print(menu.dtype)

['Pizza' 'Pasta' 'Mecroni']
<U7


## Arange
### It create an array by using the evenly spaced values over the given interval

#### np.arange(value)
#### or
#### np.arange(start, stop, step, dtype)


In [7]:
import numpy as np
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
# prog. create an array by using 'arange'
import numpy as np
y = np.arange(4, 13)
print(y)

[ 4  5  6  7  8  9 10 11 12]


## Create a linear-spaced array items

t is similar to arange function, it doesn't allow step size, instead of that, it only returns evenly seprated values over a specified period.
The system implicitly calculated the step size.

### Syntax:
   ### np.linspace(start, stop, num, endpoint)

In [9]:
import numpy as np
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [10]:
#Prog. Linspace
import numpy as np
a = np.linspace(8, 64, 3)
print(a)

[ 8. 36. 64.]


In [11]:
#Prog.
import numpy as np
b = np.linspace(8, 64, 5, endpoint=False)
print(b)

[ 8.  19.2 30.4 41.6 52.8]


In [12]:
#Prog. Create a sequence of 10 values in range 0 to 5
import numpy as np
x = np.linspace(0, 5, 10)
print(x)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Log-spaced
It create an array by using the number that are evenly seprated a log scale

In [13]:
import numpy as np
np.logspace(-2, 2, 5)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [14]:
#Prog.
x = np.logspace(10, 20, 5)
print(x)

[1.00000000e+10 3.16227766e+12 1.00000000e+15 3.16227766e+17
 1.00000000e+20]


In [15]:
#Prog.
y = np.logspace(6, 10, 3)
print(y)

[1.e+06 1.e+08 1.e+10]


In [16]:
#Prog.
k = np.logspace(10, 20, 3, base = 2)
print(k)

[1.024000e+03 3.276800e+04 1.048576e+06]


In [17]:
#Prog. Finding the dimension of an array

import numpy as np

k = np.array([[6, 8, 9],
             [7, 12, 19],
             [12, 16, 19]])

#ndim: function is used to find the dimension of an array

print(k.ndim)

2


In [18]:
#Prog.

p = np.array([6, 7, 9])

#dimension of an array p
print(p.ndim)

1


In [19]:
#Prog. Find the data type of each item of an array

import numpy as np

t = np.array([[6, 7, 13],
             [12, 78, 6]])

# dtype: function is used to find the data type of an array item

print(t.dtype)

int64


In [20]:
#Prog.

s = np.array([6.9, 7.2, 9.5])

#data type of an array item
print(s.dtype)

float64


In [21]:
#Prog. Shape & size of an array

import numpy as np

k = np.array([[13, 6, 89, 6], [6, 8, 47, -13]])

# size: function is used to find the size of an array

print("Sie of an array", k.size)

# shape: fuxtion is used to find the shape of an array

print("shape of an array:", k.shape)

Sie of an array 8
shape of an array: (2, 4)


### Reshaping of an array object
Numpy used reshape() function to change rows & columns in multi-dimensional array

In [22]:
#Prog. Reshape of an array

import numpy as np

x = np.array([[14, 21, 28], [51, 19, 24]])

#Shape of an array
print("Shape of an array", x.shape)

#Reshape of an array
k = x.reshape(3,2)

print(k.shape)

Shape of an array (2, 3)
(3, 2)


### Silicing in an array
Silicing is the way to extract a range of elements from an array.
There are three types of index/slicing 
1. Field Access
2. Basic Silicing
3. Advanced Silicing

A python silice object is constructed by the given 'Start', 'Stop', 'Step' parameter to built-in function.

In [23]:
#Prog.
import numpy as np

x = np.arange(10)
print("Array:",x)

# slicing
s = slice(2, 7, 2)
print("Siliced array", x[s])

Array: [0 1 2 3 4 5 6 7 8 9]
Siliced array [2 4 6]


In [24]:
#prog.

s = np.array([61, 13, 97, 78, 45, 69, 11, 8, 12, 23, 56])

#slicing

k = slice(3, 8, 3)

print(s[k])

[78 11]


In [25]:
#Prog.

t = np.array([[6,7], [2, 6], [4,5]])
#slicing
print(t[0,1])

print(t[1,1])

print(t[2,1])

7
6
5


In [26]:
#Prog.

x = np.array([[25, 68, 19],
             [16, 12, 18],
             [11, 19, 40]])

print(x[2, 2])
print(x[0, 0])
print(x[1, 2])

40
25
18


In [27]:
#Prog.

x = np.arange(10)
print(x)

y = x[2:7:2]
print(y)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [28]:
#Prog.
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
print(x[2:])

[2 3 4 5 6 7 8 9]


In [30]:
print(x[3:5])

[3 4]


In [31]:
print(x[3:5:2])

[3]


In [32]:
print(x[:2])

[0 1]


In [33]:
print(x[:-3])

[0 1 2 3 4 5 6]


In [34]:
print(x[-3:])

[7 8 9]


### Maximum, minimum, Sum elements of an array

In [35]:
#Prog.
import numpy as np

a = np.array([6, 7, 8, 9, 13, 25, 0, 3, 6, 61])

#max(): function is used to find the maximum element of an array
print("maximum element", a.max())

#min(): function is used to find the minimum element of an array
print("minimum element:", a.min())

#sum(): function is used to calculate the sum of elements of an array
print("Sum of an array element:", a.sum())

maximum element 61
minimum element: 0
Sum of an array element: 138


### Array axis
axis = 0 - represent column
axis = 1 - represent column

In [36]:
#Prog.

import numpy as np

a = np.array([[4,6,83], [6, 3, 81]])

#find the maximum element from the column
b = a.max(axis = 0)
print(b)

#find the minimum element from the column
c = a.min(axis = 0)
print(c)

#find the maximum element from the all rows
d = a.max(axis = 1)
print(d)

#find the minimum element from the all rows
e = a.min(axis = 1)
print(e)

#sum of all rows
f = a.sum(axis = 1)
print(f)

#sum of all columns
g = a.sum(axis = 0)
print(g)

[ 6  6 83]
[ 4  3 81]
[83 81]
[4 3]
[93 90]
[ 10   9 164]


### Square root and Standard Deviation of an array
sqrt() - square root
std() - standard deviation

In [37]:
#Prog. Finding the square root and standard deviation of an element of an array

import numpy as np

a = np.array([[1, 2, 30],
             [10, 15, 4]])

#sqrt()
b = np.sqrt(a)
print(b)

#std()
c = np.std(a)
print("\n",c)

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]

 10.044346115546242


In [38]:
#Prog. Array to bigin with 3 X 3 matrix

import numpy as np

a = np.array([[4, 6, 14],
             [16, 21, 29],
             [15, 36, 14]])

print(a)

[[ 4  6 14]
 [16 21 29]
 [15 36 14]]


In [39]:
print(a.ndim)

2


In [40]:
# print the elements fron 2nd column
print(a[..., 1])

[ 6 21 36]


In [41]:
#print the element from 3rd column
print(a[..., 2])

[14 29 14]


In [42]:
#print the element from first row
print(a[0,...])

[ 4  6 14]


### Arithmetic Operations on Array

In [43]:
#Prog.

import numpy as np

a = np.array([[1, 2, 3], [10, 6, 8]])
b = np.array([[16, 14, 32], [6, 23, 21]])

#addition
c = a + b
print(c)

[[17 16 35]
 [16 29 29]]


In [44]:
#substraction
d = a-b
print(d)

[[-15 -12 -29]
 [  4 -17 -13]]


In [45]:
#multiplication
e= b*a
print(e)

[[ 16  28  96]
 [ 60 138 168]]


In [46]:
#divide
f = a % b
print(f)

[[1 2 3]
 [4 6 8]]


In [47]:
#Prog.
a = np.array([4, 6, 9])
print(a)

[4 6 9]


In [48]:
b = 8
print(b)

8


In [49]:
c = a + b
print(c)

[12 14 17]


In [50]:
#Prog. Array operator

import numpy as np
x = np.arange(4)
x

array([0, 1, 2, 3])

In [51]:
#scalar adition is element wise
x + 10

array([10, 11, 12, 13])

In [52]:
#scalar multiplication element wise
x*2

array([0, 2, 4, 6])

In [53]:
#Array addition element wise
x + x

array([0, 2, 4, 6])

### dot product (or generally matrix multiplication)
It is done with function

In [54]:
#Prog.
import numpy as np
a = np.dot(6, 3)
a

18

In [55]:
#Prog
a = np.dot([2j, 3j],[5j, 8j])
a

(-34+0j)

In [56]:
#Prog.
a = np.array([[6, 8], [9, 12]])
b = np.array([[12, 18], [19, 21]])
c = np.dot(a,b)
c

array([[224, 276],
       [336, 414]])

### Concatenation
1. It a Numpy function used to combine multiple arrays with same shape.
2. Stacking of arrays can be done both horizontally and vertically wrt axis
3. axis = 0 is default
4. Syntax: np.concatenate((a1, a2,...), axis)

In [57]:
#Prog.
import numpy as np
a = np.array([[1, 6], [7, 8]])
b = np.array([[7, 9]])

z = np.concatenate((a,b))
z

array([[1, 6],
       [7, 8],
       [7, 9]])

In [58]:
#Prog. concatenate wrt axis = 0

z =np.concatenate((a, b), axis = 0)
z

array([[1, 6],
       [7, 8],
       [7, 9]])

In [59]:
#Prog. cocatenate wrt axis = 1

z = np.concatenate((a, b.T), axis = 1)
z

array([[1, 6, 7],
       [7, 8, 9]])

In [60]:
#Prog. concatenate wrt axis = None
z = np.concatenate((a, b), axis = None)
z

array([1, 6, 7, 8, 7, 9])

In [61]:
# Masked Array
import numpy as np
x = np.ma.arange(3)
x

masked_array(data=[0, 1, 2],
             mask=False,
       fill_value=999999)

In [62]:
y = np.arange(3,6)
y

array([3, 4, 5])

In [63]:
x[1] = np.ma.masked
x

masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)

In [64]:
z1 = np.concatenate([x, y])

In [65]:
z1

masked_array(data=[0, 1, 2, 3, 4, 5],
             mask=False,
       fill_value=999999)

In [66]:
z2 = np.ma.concatenate([x,y])

In [67]:
z2

masked_array(data=[0, --, 2, 3, 4, 5],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)

### Append
1. add or append new value into existing array.
2. The function add the new value at the end of the array
3. Syntax: np.append(arr, values, axis=None)

In [68]:
#Prog.
import numpy as np
a = np.array([[10, 20, 30],
             [30, 40, 50],
             [60, 70, 80]])
b = np.array([[11, 21, 33],
             [14, 16, 38],
             [23, 29, 18]])

# append

c = np.append(a,b)
c

array([10, 20, 30, 30, 40, 50, 60, 70, 80, 11, 21, 33, 14, 16, 38, 23, 29,
       18])

In [69]:
#append wrt axis = 0
c = np.append(a,b, axis = 0)
c

array([[10, 20, 30],
       [30, 40, 50],
       [60, 70, 80],
       [11, 21, 33],
       [14, 16, 38],
       [23, 29, 18]])

In [70]:
#append wrt axis = 1
c = np.append(a,b, axis=1)
c

array([[10, 20, 30, 11, 21, 33],
       [30, 40, 50, 14, 16, 38],
       [60, 70, 80, 23, 29, 18]])

## Random 
It is used to generate random numbers.
1. Simple random data:
         np.random.rand(d0, d1,...dn)
 This function is used to generate random number or values in given shape

2. np.random.randn(d0, d1, d2,....dn)
         This function of random module returns a sample from the 'standard normal' distribution.
         
3. np.random.randint(low[, high, size, dtype)
           It generate random integers from inclusive(low) to inclusive (high)

In [71]:
#Prog. 
import numpy as np
x =np.random.rand(5, 3)
x

array([[0.18594265, 0.05897964, 0.60637689],
       [0.67010223, 0.15555275, 0.65830304],
       [0.35071491, 0.73665471, 0.75986245],
       [0.75905915, 0.50327367, 0.24889071],
       [0.57307249, 0.4994285 , 0.5052205 ]])

In [72]:
#Prog.
y = np.random.randn(2,2)
y

array([[-2.02571503, -0.77971308],
       [-1.24818959,  1.04448967]])

In [73]:
b = np.random.randn()
b

-0.5445245211423408

In [74]:
#Prog.
a = np.random.randint(3, size=5)
a

array([0, 1, 1, 0, 2])

### NumPy Zeros
1. It generate an array containing zeros
2. Syntax:
          np.zeros(size, dtype, order)
3. bydefault dtype is float
4. order is c-major or f-major

In [75]:
import numpy as np
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [76]:
import numpy as np
a = np.zeros((6), dtype=int)
a

array([0, 0, 0, 0, 0, 0])

In [77]:
a =np.zeros((6, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
import numpy as np
x = (3, 4)
y = np.zeros(x, dtype=int)
y

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [79]:
#NumPy Once

import numpy as np
x = np.ones(3)
x

array([1., 1., 1.])

In [80]:
x = np.ones(6, dtype=int)

In [81]:
x

array([1, 1, 1, 1, 1, 1])

In [89]:
#Creaing Numpy Array fron an existing data

#np.asarry()  - It convert into numpy array from the existing data like list or touples.
# Syntax:
    # np.asarray(sequence, dtype=None, order="None")

import numpy as np
#create an numpy array from list
x1 =[6, 9, 8, 7]   #list
print(x1)
x2 = np.asarray(x1)
print(type(x2))
print(x2)

[6, 9, 8, 7]
<class 'numpy.ndarray'>
[6 9 8 7]


In [91]:
#creating numpy array using touple
t = (2, 7, 9, 8, 12)
x = np.asarray(t)
print(t)
print(x)
print(type(x))

(2, 7, 9, 8, 12)
[ 2  7  9  8 12]
<class 'numpy.ndarray'>


In [94]:
#create an numpy array from more than one list
l = [[6, 8, 9, 12, 9], [78, 23, 89]]
print(l)
a = np.asarray(l)
print(a)
print(type(a))

[[6, 8, 9, 12, 9], [78, 23, 89]]
[list([6, 8, 9, 12, 9]) list([78, 23, 89])]
<class 'numpy.ndarray'>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  after removing the cwd from sys.path.
