In [1]:
import numpy as np
import pandas as pd

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [3]:
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [4]:
irisdata = pd.read_csv(url, names = colnames)

In [5]:
irisdata.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
x = irisdata.drop('Class', axis = 1)

In [7]:
y = irisdata['Class']

In [8]:
x.head()

sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [9]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Class, dtype: object

In [10]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 100)

# poly

In [11]:
svcClassifier = SVC(kernel = 'poly', degree = 8)

In [12]:
svcClassifier.fit(x_train, y_train)

C:\Users\mugee\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [13]:
irisdata.shape

(150, 5)

In [14]:
y_pred = svcClassifier.predict(x_test)

In [15]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [16]:
print('Accuracy:', accuracy_score(y_test, y_pred)*100)

Accuracy: 96.66666666666667


In [17]:
print('Confusion Matrix\n', confusion_matrix(y_test, y_pred))

Confusion Matrix
 [[11  0  0]
 [ 0  5  1]
 [ 0  0 13]]


In [18]:
print('classification report:\n', classification_report(y_test, y_pred))

classification report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      0.83      0.91         6
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.97        30
      macro avg       0.98      0.94      0.96        30
   weighted avg       0.97      0.97      0.97        30



# rbf

In [19]:
from sklearn.svm import SVC
clf = SVC(kernel = 'rbf')
clf.fit(x_train, y_train)

C:\Users\mugee\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [20]:
y_pred1 = clf.predict(x_test)

In [21]:
print('Accuracy:', accuracy_score(y_test, y_pred1)*100)

Accuracy: 96.66666666666667


# linear

In [22]:
clf1 = SVC(kernel = 'linear')
clf1.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [23]:
y_pred2 = clf1.predict(x_test)

In [24]:
print('Accuracy:', accuracy_score(y_test, y_pred2)*100)

Accuracy: 100.0


# Sigmoid

In [25]:
clf2 = SVC(kernel = 'sigmoid')
clf2.fit(x_train, y_train)

C:\Users\mugee\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [26]:
y_pred3 = clf2.predict(x_test)

In [28]:
print('Accuracy:', accuracy_score(y_test, y_pred3)*100)

Accuracy: 20.0


In [30]:
print('confusion matrix:\n', confusion_matrix(y_test, y_pred3))

confusion matrix:
 [[ 0 11  0]
 [ 0  6  0]
 [ 0 13  0]]


In [32]:

print('Classificsation Report:\n', classification_report(y_test, y_pred3))

Classificsation Report:
                  precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        11
Iris-versicolor       0.20      1.00      0.33         6
 Iris-virginica       0.00      0.00      0.00        13

       accuracy                           0.20        30
      macro avg       0.07      0.33      0.11        30
   weighted avg       0.04      0.20      0.07        30



C:\Users\mugee\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


#### Comperison of kernel Performance:
#### If we compare the performance of different types of kernels we can see that the sigmoid kernel performance is worst
#### This is due the reason that sigmoid functions returns 2 values 0 and 1. it is more suitable for binary classification 